Django/django girls tut/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    path("", views.post_list, name="list"),
    path('<int:pk>/', views.detail, name='detail'),
    path('create/', views.create, name='create'),
    path('<int:pk>/edit/', views.edit, name='edit')
]

Django/django girls tut/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls'))
]

Django/django girls tut/blog/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone


class Post(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()
    

    def __str__(self):
        return self.title

Django/django girls tut/blog/forms.py
from django import forms
from .models import Post

class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields =('title', 'text')

Django/django girls tut/blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from .models import Post
from .forms import PostForm


def post_list(request):
    posts = Post.objects.filter(published_date__lte=timezone.now()).order_by('published_date')
    return render(request, 'blog/post_list.html', locals())


def detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    return render(request, 'blog/detail.html', locals())


def create(request):
    if request.method == 'POST':
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.published_date = timezone.now()
            post.save()
            return redirect('blog:detail', pk=post.pk)
    else:
        form = PostForm()
        return render(request, 'blog/edit.html', locals())


def edit(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.published_date = timezone.now()
            post.save()
            return redirect('blog:detail', pk=post.pk)
    else:
        form = PostForm(instance=post)
    return render(request, 'blog/edit.html', {'form': form})

Django/django girls tut/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
		<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
		<link rel="stylesheet" href="{% static 'css/blog.css' %}">
		<link href="https://fonts.googleapis.com/css?family=Lobster&subset=latin,cyrillic" rel="stylesheet" type="text/css">
		<title>Blog</title>
	</head>
	<body>
		<div class="page-header">
			{% if user.is_authenticated %}
				<a href="{% url 'blog:create' %}" class="top-menu"><span class="glyphicon glyphicon-plus"></span></a>
			{% endif %}
			<h1><a href="{% url 'blog:list' %}">Django Girls Blog</a></h1>

		</div>
		<div class="content container">
			<div class="row">
					<div class="col-md-8">
					{% block content %}
					{% endblock %}
					</div>
			</div>
		</div>
	</body>
</html>

Django/django girls tut/templates/blog/detail.html
{% extends "blog/base.html" %}

{% block content %}
	<div class="post">
		{% if post.published_date %}
			<div class="date">
				{{ post.published_date }}
			</div>
		{% endif %}
		{% if user.is_authenticated %}
			<a class="btn btn-default" href="{% url 'blog:edit' pk=post.pk %}"><span class="glyphicon glyphicon-pencil"></span></a>
		{% endif %}
		<h1>{{ post.title }}</h1>
		<p>{{ post.text|linebreaksbr }}</p>
	</div>
{% endblock %}

Django/django girls tut/templates/blog/edit.html
{% extends "blog/base.html" %}

{% block content %}
	<h1>New post</h1>
	<form method="POST" class="post-form">
		{% csrf_token %}
		{{ form.as_p }}
		<button type='submit' class='save btn btn-default'>Save</button>
	</form>
{% endblock content %}

Django/django girls tut/templates/blog/post_list.html
{% extends "blog/base.html" %}

{% block content %}
	{% for post in posts %}
	<div class="post">
		<div class="date">
			<p>Опубликовано: {{ post.published_date }}</p>
		</div>
		<h1><a href="{% url 'blog:detail' pk=post.pk %}">{{ post.title }}</a></h1>
		<p>{{ post.text|linebreaksbr }}</p>
	</div>
	{% endfor %}
{% endblock content %}